version: 0.2
env:
  variables:
    ECR_REPO_NAME: fuel
    SPRING_DATASOURCE_URL: jdbc:mysql://fueldb.cezw8cgiq5bj.us-east-1.rds.amazonaws.com:3306/fuelDB
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: rootroot
    SPRING_PROFILES_ACTIVE: cloud

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - mvn install -DskipTests

  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - ECR_REGISTRY=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=latest
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker images...
      - docker-compose build

  post_build:
    commands:
      - echo Pushing Docker images...
      - docker-compose push
