identity.provider.port=9090
fuel.service.port=9091

fuel.service.host=http://fuel-load-balancer-1393831740.us-east-1.elb.amazonaws.com
identity.provider.host=http://fuel-load-balancer-1393831740.us-east-1.elb.amazonaws.com